# Read, Listen, and Speak


### Types of Dialogue

While every genre of game and every company has its own specific dialogue type and terminology, they all fall into three broad categories: Ambient Dialogue , Interactive Dialogue, and Cutscenes.

### Ambient Dialogue

In this book, “ambient dialogue” means any talking that happens during gameplay , whether it’s dialogue by the player, by AI companions, by a voice-over a radio headset, or by characters the player passes in the street. This is dialogue that is prompted by in-game events and triggers, such as:

- Entering an area
- Taking damage in combat
- Attempting an action

The player is free to listen to or ignore such dialogue, though frequently it does contain valuable instructions from NPCs or radio-headset voices, such

### Interactive Dialogue

“Interactive Dialogue” refers to any game system in which the dialogue pauses the action to allow the player to select responses from a list, wheel, or any other presentation of multiple options. What these systems have in common is that they allow the player to take an active role in the dialogue.

Cutscenes

For the book’s purposes, a cutscene refers to any dialogue that both:

- occurs outside of gameplay;
- does not off er player choice.

These are the “mini-movie” moments that usually occur to highlight particularly spectacular moments in the game. Cutscene dialogue is usually sparse and paired with extensive animated sequences that occur outside of

### Narratives


### Vocabulary

