# Roadmap

The near-term focus will be on **indigenous**, **native**, and **under-represented languages** other than those transplanted by foreign influence and/or exceptionally well-represented by widely available language learning resources such as Arabic, English, French, Mandarin, etc. The initial priority will be to include languages that meet the following criteria:

- In active use by a sizable population where the learning of such language creates enhanced communication opportunities across cultures and ethnic groups.
- Is a language that may not be formally taught or where learning resources are limited.

Our current focus is on ==Luganda==, an indigenous language spoken in Uganda by an estimated 4+ million people.

Candidates for future development might include, for example:

- Afrikaans : South Africa
- Amharic : Ethiopia
- Bemba : Zambia
- Berber : North Africa
- Chichewa : Malawi
- Fula / Fulfude : Senegal, Guinea, Mauritania, Gambia, Mali, Burkina Faso, Ghana, Nigeria, Cameroon, Togo, Chad, Sudan, Somalia, Ethiopia, Uganda.
- Hausa : Nigeria+
- Igbo : Nigeria, Cameroon, Equatorial Guinea
- Kinyarwanda : Rwanda
- Kirundi : Burundi
- Lingala : DRC, Rep of Congo
- Oromo : Ethiopia, Kenya, Somalia and Egypt
- Pidgin : Nigeria
- Shona : Zimbabwe
- Somali : Somalia
- Swahili : Kenya, Tanzania
- Tigrigna : Ethiopia, Eritrea
- Tswana : Botswana
- Tumbuka : Malawi and Zambia
- Wolof : Senegal
- Xhosa : South Africa, Botswana and Lesotho
- Yoruba : Nigeria, Benin and Togo
- Zulu : South Africa

*Note*: although the languages listed above are largely spoken in Africa, the project is **equally committed to all regions and languages** fitting the scope criteria.