# The World

### Gameplay Overview

Gameplay is defined as:

> *the characteristic way in which the action of a game (such as a video game) occurs or is experienced*[^1]

[^1]:Merriam-Webster.com Dictionary



KOMPRENI? is a hybrid 2.ZD game with side-scrolling world navigation combined with an RPG style level play based on an orthographic, 3/4 axonometric 45 degree top-down perspective. The blending of styles was influenced by the game play and art styles of games such as such as Detention, Inside, Eastward, Tails Noir, and Disco Elysium to name a few. The target platform is currently for desktop and potentially web to take advantage of a 16:9 aspect ratio and high resolution.

# Street View

These scenes are based on a minimum five ( 5 ) depths of field ( z-order ) as follows:

* parallax background
* eye catching interest background
* focus ( entry points to levels )
* walking path ( sidewalk )
* foreground ( passing vehicles, characters, etc. )

# Level View

* perspective change to top down 3/4 45 degree view
* 4 way character movement

This enables use of the full screen space to build out the story and stage with all the needed characters and props.