# Compositing


Compositing is the process of taking several visual elements from different sources and combining them into a single video.


### Studio staging

Have you ever gone to a professional photographer's studio for a family portrait?  If so, our studio setup will be similar.  We'll position our character so the image rendering is exactly as we will want it when placed in our game scenes.  Here's what we need to do:

- Create a studio setting to help us visualize the **look and feel**.
- Configure the **camera** using a standard configuration so all our rendered assets will have the same relative perspective.
- Configure the **lights** to take advantage of the 3D environment shadows  as an aid for our post-image art work.
- Configure post-processing effects such as ambient occlusion, ssao, etc.

This [video](https://www.vilijcorps.org) [^1] shows the entire process step-by-step resulting in this template blend file.

[^1]: Please watch the videos, like, and subscribe if the information is useful to you.  Any potential to monetize our how-to videos provides a fund raising opportunity for the continued development of the project. We, and those who benefit from the project, are very grateful for your support.
