# Scenario-Based

Goal: Identify the goal for the level: What do you want the player to
experience?

- Scenarios: Identify the specific types of gameplay scenarios that can exist within the game and that will help to satisfy the stated goals. For example, if the goal is to provide a sense of empowerment, then scenarios that allow the player to tackle and defeat a wave of enemies could be appropriate.

- Moments: Scenarios can then be broken down into scripted moments that make the scenarios more exciting, dynamic, and rewarding. For example, if the scenario is to tackle a wave of enemies, then this might comprise moments such as enemies bursting through the floor unexpectedly, enemies grabbing and holding down the PC, or enemies using the environment against the player.

- Actions: Finally, we have the specific actions that the player can perform in order to meet the challenge presented in gameplay moments.

In the given example, this might involve mechanics such as punching, kicking, throwing objects, using weapons, and so on.