# Transmedia Storytelling

Transmedia storytelling relates to the creation of stories that span different media – a transmedia story is ‘a particular narrative structure that expands through both different languages (verbal, iconic, etc.) and media (cinema, comics, television, video games, etc.)’ (Pietschmann, Völkel, & Ohler, 2014).

engagement with the story and its wider story world may involve reading comics, using apps, watching films or reading information scattered across a range of published stories including novels, comics and other texts. The intention of such an approach is to reach the audience through different media and integrate them more fully into the story.

In his book, You’re Gonna Need a Bigger Story, Houston Howard describes transmedia storytelling as “the art of extending a story across multiple mediums and multiple platforms in a way that creates a better business model for creators and a better experience for the audience.” [16]

Transmedia storytelling mimics daily life, making it a strong constructivist pedagogical tool for educational uses.[23]

Transmedia storytelling allows for the interpretation of the story from the individual perspective, making way for personalized meaning-making[23] - and in the case of fully participatory projects - allows participants to become co-creators of the story.[27]

Anders Gronstedt and Marc Ramos say "At the core of every training challenge is a good story waiting to be told. More and more, these stories are being told across a multitude of devices and screens, where they can reach 
learners more widely, and engage with them more deeply."[30]

For the purpose of studying transmedia storytelling and how information becomes spreadable across multiple media platforms, we can look at four strategies for expanding the narrative world of media texts. 

- First is the creation of interstitial microstories. 
- The final strategy is user-generated content platforms leveraging open source story-creation that allow users to add to the world and journey.

- the game
- video game play
- graphic novel
- web site
- social media


 16 Howard, Houston (2017). You're gonna need a bigger story : the 21st century survival guide to not just writing stores, but building super stories. [United States?]. ISBN 978-0-692-84900-2. OCLC 1122543816.

 23 Jenkins, H. "Transmedia Storytelling and Entertainment: An Annotated Syllabus", Continuum: Journal of Media & Cultural Studies, 24:6, 943-958 2010.

 27 Gambarato, Renira Rampazzo; Dabagian, Lilit (2016-10-01). "Transmedia dynamics in education: the case of Robot Heart Stories". Educational Media International. 53 (4): 232. doi:10.1080/09523987.2016.1254874. ISSN 0952-3987. S2CID 63575976.

 30 Gronstedt, Anders; Ramos, Marc (January 7, 2014). Learning Through Transmedia Storytelling (Infoline). ASTD. ISBN 978-1562869519.