# Path to Proficiency

As Vilij is a multi-language learning platform, its success is hinged on a capability to promote skill development for listening, speaking, reading, and writing. To ensure its value for those we hope it benefits, we needed to fully understand the “linguistic” criteria for language learning and gaining fluency. Only after full examination of the various measures and best practices can I have reasonable assurances that Vilij is a viable project that can truly realize its promised benefits and value.

Drawing from a wide range of references, We've aligned the learning experience with practical learning objectives and goals.

-   1000 words allow you to understand about 80% of the common language which surrounds you.

-   3000 words allow you to understand about 95% of most ordinary texts.

-   5000 words allow you to understand about 98% of most ordinary text.

-   6,000 to 7,000 words to understand 98% of spontaneous spoken language.

-   7,000 words to watch and understand a movie.

-   8,000 words to read a newspaper.

-   8,000-9,000 words to read a novel.

-   10000 words allow you to understand about 99% of most texts

Another key aspect of language learning is to clearly realize the progress and skills gained from the investment of time. Vilij implements a scoring and progress tracking system that aims to “describe” a player's gains towards language competency and fluency. The measures are based on a simplified interpretation and implementation of three frameworks: the Common European Framework of References (CEFR), The Interagency Language Roundtable (ILR) developed by the United States Foreign Service Institute, and the American Council on the Teaching of Foreign Languages scale (ACTFL)25.

The fact is, immersion and context are critical to the language learning experience. This point is reinforced by Luca Lampariello24, a well-known polyglot with a popular language learning YouTube channel, who asserts that “context is king”. He suggests that good guessing skills are truly important when it comes to acquiring a foreign language. What happens is that you will eventually learn words through repeated exposure, in different contexts, at different places. This is called assimilation. And this is your aim when acquiring a foreign language.

### Measures of Language Proficiency Integrated in to the Game Platform

+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Measure                          | Criteria                                                                                                                                                                                                                                           |
+==================================+====================================================================================================================================================================================================================================================+
| Basic A1 (CEFR)                  | -   basic introductions and answering questions about personal details                                                                                                                                                                             |
|                                  |                                                                                                                                                                                                                                                    |
| Elementary (S-1) (ILR)           | -   communicate minimally with formulaic and rote utterances, lists, and phrases                                                                                                                                                                   |
|                                  |                                                                                                                                                                                                                                                    |
| Novice L / M (ACTFL              | -   250 Words                                                                                                                                                                                                                                      |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Basic A2 (CEFR)                  | -   describe in simple terms aspects of his/her past, environment and matters related to his/her immediate needs                                                                                                                                   |
|                                  |                                                                                                                                                                                                                                                    |
| Elementary (S-1) (ILR)           | -   perform routine tasks requiring basic exchanges of information                                                                                                                                                                                 |
|                                  |                                                                                                                                                                                                                                                    |
| Novice M / H (ACTFL)             | -   communicate minimally with formulaic and rote utterances, lists, and phrases                                                                                                                                                                   |
|                                  |                                                                                                                                                                                                                                                    |
|                                  | -   500 words                                                                                                                                                                                                                                      |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Independent B1 (CEFR)            | -   can deal with most daily life situations in the country where the language is spoken                                                                                                                                                           |
|                                  |                                                                                                                                                                                                                                                    |
| Limited working (S-2) (ILR)      | -   can describe experiences, dreams and ambitions and give brief reasons for opinions and goals                                                                                                                                                   |
|                                  |                                                                                                                                                                                                                                                    |
| Intermediate H / M / L (ACTFL)   | -   create with language, initiate, maintain, and bring to a close simple conversations by asking and responding to simple questions                                                                                                               |
|                                  |                                                                                                                                                                                                                                                    |
|                                  | -   1000 Words                                                                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Independent B2 (CEFR)            | -   can understand the themes of complex texts on both concrete and abstract topics and will have achieved a degree of fluency and spontaneity, which makes interaction with native speakers possible without significant strain for either party. |
|                                  |                                                                                                                                                                                                                                                    |
| Professional Working (S-3) (ILR) | -   narrate and describe in past, present, and future                                                                                                                                                                                              |
|                                  |                                                                                                                                                                                                                                                    |
| Advanced H / M / L (CTFL)        | -   deal effectively with an unanticipated complication                                                                                                                                                                                            |
|                                  |                                                                                                                                                                                                                                                    |
|                                  | -   3000 Words                                                                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Proficient C1 (CEFR)             | -   understand a wide range of longer texts                                                                                                                                                                                                        |
|                                  |                                                                                                                                                                                                                                                    |
| Full professional (S-4) (ILR)    | -   recognize subtleties and implicit meaning                                                                                                                                                                                                      |
|                                  |                                                                                                                                                                                                                                                    |
| Superior (ACTFL)                 | -   produces clear, well-structured and detailed text on complex subjects                                                                                                                                                                          |
|                                  |                                                                                                                                                                                                                                                    |
|                                  | -   shows controlled use of organizational patterns, connectors and cohesive devices                                                                                                                                                               |
|                                  |                                                                                                                                                                                                                                                    |
|                                  | -   discuss topics extensively, support opinions, hypothesize                                                                                                                                                                                      |
|                                  |                                                                                                                                                                                                                                                    |
|                                  | -   deal with linguistically unfamiliar situations                                                                                                                                                                                                 |
|                                  |                                                                                                                                                                                                                                                    |
|                                  | -   4000 words                                                                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Proficient C2 (CEFR)             | -   understand virtually everything heard or read                                                                                                                                                                                                  |
|                                  |                                                                                                                                                                                                                                                    |
| Native or bilingual (S-5) (ILR)  | -   expressing oneself spontaneously, very fluently and precisely                                                                                                                                                                                  |
|                                  |                                                                                                                                                                                                                                                    |
| Distinguished (ACTFL)            | -   converse in highly complex situations                                                                                                                                                                                                          |
|                                  |                                                                                                                                                                                                                                                    |
|                                  | -   ability to tailor language to specific audience, persuade, negotiate                                                                                                                                                                           |
|                                  |                                                                                                                                                                                                                                                    |
|                                  | -   deal with nuance and subtlety                                                                                                                                                                                                                  |
|                                  |                                                                                                                                                                                                                                                    |
|                                  | -   10,000+ words                                                                                                                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+