# Characters


## Identity and Personality


### The Player

point of view

STEREOTYPE: a generalized, non-contextual portrait of an individual that does not take into account unique qualities all individuals possess.

> To write characters the player will want to know and play with, we first must respect them ... We must give them a life within the game, not just a gameplay reason for being there ... Characters drive the story. If they are boring or derivative ... the story will be the same. [^1]

[^1]: Character Development and Storytelling for Games

Hero - Women

### Non-Player Characters ( NPCs )


> Many games treat minor characters as functionaries only, assigning them a single role to play, and shoving a line or two of dialogue ... This is ignoring all the many ways they can support the story and the overall game experience. [^2]

[^2]: Character Development and Storytelling for Games


### Character Traits

> When it comes to nonverbal communication, the body is perhaps the most obvious channel for expression. Body expression can be a useful means of communicating the thought process, emotions, and personality of a character regardless of the placement or orientation of the camera. In contrast, the finer details of facial expression may require a close-up to be easily recognized.

#### gestures, poses, and animations

We don’t like stairs very much in video games.  The balcony scene from Romeo and Juliet would be drastically changed if Juliet happened to live on the ground floor... [^3]

[^3]: Character Development and Storytelling for Games

We can not be lazy.

Dev Examples

- Papa Squat and the Butt Cracks

#### facial expressions and mannerisms

> We don’t have the luxury of all the nuances of expression that the human face can reveal. When it is rendered and animated in our games, we see a broad parody, carefully modeled on the muscle contractions that occur when humans feel emotion, but soulless. We can help the illusion with astute voice acting, but it remains a construct and nothing more. [^4]

[^4]: Character Development and Storytelling for Games

We can not be lazy

- faceless
- cute
- hero
- enemy

When it comes to emotional facial expressions, however, there is a tendency to focus on a core six emotional expressions that are commonly recognized as being culturally universal. In other words, these six expressions are believed to be embedded in human nature, as people from all over the world use and recognize them. The six universal expressions of emotion are commonly stated to be joy, sadness, anger, fear, disgust, and surprise.