# Flow and Zone

Enabling a flow state is one of the most sought-after achievements for a game. While conventional video game design may focus on the balance of challenge versus progression, as a learning platform there are additional considerations. 

The enjoyment is in the learning, in the perfect balance between player skill and the challenge presented.

The five most common experiences of game feel are:

- The aesthetic sensation of control
- The pleasure of learning, practicing and mastering a skill
- Extension of the senses
- Extension of identity
- Interaction with a unique physical reality within the game

The Feel of Everyday Things

Every new animator has to learn these principles. They comprise a universally applicable set of non-negotiable aesthetic guidelines.

1 Frank Thomas and Ollie Johnston’s “Principles of Physical Animation ” are online at http://www.frankandollie.com/PhysicalAnimation.html


Rules Metrics:
- Collect 100 coins to get a star.
- dialogue points
- vocabulary points
- experience points measured by repetition + scope (coverage of a subject) + scale (number of subjects covered)?
- level of difficulty

Game Narrative Design is the art of telling a story in a computer game using the techniques and devices available. It is the art of using gameplay and the sum of visual and acoustic methods to create an entertaining and engaging experience for players.