# Gameology Overview

As designers and developers of ==Kompreni?==, our goal is to make a **great** game. That is the ambition of every indie to AAA game developer.  But let's face the harsh reality that it is easier, perhaps even more likely, to make a bad game.

> Another risk is placing high hopes on games designed for the public good—as many nonprofits, health organizations, and social enterprises are doing—without realizing that bad game  design can undermine the most noble of ambitions. It’s quite possible to make terrible, dull, and unappealing games for learning or training or health. We need to have a language for discerning among these games—are they doing their job well or poorly? How can you tell? What makes them good?



How Games Move Us, Emotion by Design


### What can we learn from others...

Oxenfree, Detention, Deadlight, Tails Noir, Creaks, Machinarium, Dream Alone, Orphan, OddPlanet, Pinstripe, Typoman, Toby, Mosaic, Overland, Disco Elysium, The Swapper, This War of Mine, Huntdown, Journey, My Memory of Us, Gris, Cloudpunk, Beholder 2, The Missing, Nivalis, Liberated, Narita Boy, Shady Part of Me, Book of Travels, White Shadows, Dead Static Drive, Ami, Signalis, The Plane Effect, Replaced, Endzone 2, Calvino Noir, DARQ, Eastwood, INMOST, INSIDE, Monochroma, Northern Lights, Project Highrise