project:
  type: website

website:
  title: ""
  site-url: "https://www.vilijcorps.org/"
  page-navigation: true
  open-graph: true
  back-to-top-navigation: true
  google-analytics: "G-P3W0Q1HS7T"
  sidebar:
    logo: "./assets/vilijcorps.svg"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Overview"
        contents:
          - index.qmd
          - 1_1_the_experience.qmd
          - 1_2_team_and_contributers.qmd
          - 1_3_caveat-emptor.qmd
          - 1_4_sponsorship_and_fundraising.qmd
          - 1_5_language_roadmap.qmd
          - 1_6_about.qmd
          - 1_7_contact.qmd
      - section: "Language"
        contents:
          - 2_1_path_to_proficiency.qmd
          - 2_2_scenarios.qmd
          - 2_3_missions.qmd
          - 2_4_cut_scenes.qmd
      - section: "Game Design"
        contents:
          - 3_1_storytelling.qmd
          - 3_2_screenwriting.qmd
          - 3_3_storyboarding.qmd
          - 3_4_immersion.qmd
          - 3_5_not_just_a_wall.qmd
          - 3_6_emotion_and_sensation.qmd
          - 3_7_truthful_realism.qmd
      - section: "Game Development"
        contents:
          - 4_1_renpy.qmd
          - 4_2_krita.qmd
          - 4_3_blender.qmd
      - section: "Game Play"
        contents:
          - 5_1_characters.qmd
          - 5_2_the_world.qmd
          - 5_3_the_journey.qmd
          - 5_4_interaction.qmd
          - 5_5_flow_and_zone.qmd
      - section: "Content Creation"
        contents:
          - 6_1_art_style.qmd
          - 6_2_location_unique.qmd
          - 6_3_on_scene_photos.qmd
          - 6_4_stylized_post_processing.qmd
          - 6_5_compositing.qmd
      - section: "Inspiration"
        contents:
          - 7_1_visual_novels.qmd
          - 7_2_gameology.qmd
          - 7_3_sequential_art.qmd
          - 7_4_moving_images.qmd
          - 7_5_illustrated_pages.qmd
      - section: "Blog"
        contents:
          - posts.qmd
  page-footer: 
    background: dark
    foreground: light
    center: "This work by Vilij Corps is licensed under Attribution 4.0 International [ CC BY 4.0 ]" 
    right: 
      - icon: bi-cup-hot-fill
        href: "https://www.vilijcorps.org/" 
      - icon: github
        href: https://github.com/vilij-corps/vilij
      - icon: bi-chat-square-fill
        href: https://github.com/vilij-corps/vilij/discussions
      - icon: bi-envelope-at-fill 
        href: "https://www.vilijcorps.org/contact.html" 

format:
  html:
    toc: true
    toc-location: right
    theme: 
    - cosmo
    - assets/custom.scss
    page-layout: full