project:
  type: website

website:
  title: ""
  site-url: "https://www.vilijcorps.org/"
  page-navigation: true
  open-graph: true
  back-to-top-navigation: true
  google-analytics: "G-P3W0Q1HS7T"
  sidebar:
    logo: "./assets/vilijcorps.svg"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Overview"
        contents:
          - index.qmd
          - pages/1_overview/1_the_experience.qmd
          - pages/1_overview/2_team_and_contributers.qmd
          - pages/1_overview/3_caveat-emptor.qmd
          - pages/1_overview/4_sponsorship_and_fundraising.qmd
          - pages/1_overview/5_language_roadmap.qmd
          - pages/1_overview/6_about.qmd
          - pages/1_overview/7_contact.qmd
      - section: "Language Learning"
        contents:
          - pages/2_language_learning/1_path_to_proficiency.qmd
          - pages/2_language_learning/2_scenarios.qmd
          - pages/2_language_learning/3_missions.qmd
          - pages/2_language_learning/4_cut_scenes.qmd
      - section: "Game Design"
        contents:
          - pages/3_game_design/1_storytelling.qmd
          - pages/3_game_design/2_screenwriting.qmd
          - pages/3_game_design/3_storyboarding.qmd
          - pages/3_game_design/4_immersion.qmd
          - pages/3_game_design/5_not_just_a_wall.qmd
          - pages/3_game_design/6_emotion_and_sensation.qmd
          - pages/3_game_design/7_truthful_realism.qmd
      - section: "Game Development"
        contents:
          - pages/4_game_development/1_renpy.qmd
          - pages/4_game_development/2_krita.qmd
          - pages/4_game_development/3_blender.qmd
      - section: "Game Play"
        contents:
          - pages/5_game_play/1_characters.qmd
          - pages/5_game_play/2_the_world.qmd
          - pages/5_game_play/3_the_journey.qmd
          - pages/5_game_play/4_interaction.qmd
          - pages/5_game_play/5_flow_and_zone.qmd
      - section: "Content Creation"
        contents:
          - pages/6_content_creation/1_art_style.qmd
          - pages/6_content_creation/2_location_unique.qmd
          - pages/6_content_creation/3_on_scene_photos.qmd
          - pages/6_content_creation/4_stylized_post_processing.qmd
          - pages/6_content_creation/5_compositing.qmd
      - section: "Inspiration"
        contents:
          - pages/7_inspiration/1_visual_novels.qmd
          - pages/7_inspiration/2_gameology.qmd
          - pages/7_inspiration/3_sequential_art.qmd
          - pages/7_inspiration/4_moving_images.qmd
          - pages/7_inspiration/5_illustrated_pages.qmd
      - section: "Blog"
        contents:
          - posts.qmd
  page-footer: 
    background: dark
    foreground: light
    center: "This work by Vilij Corps is licensed under Attribution 4.0 International [ CC BY 4.0 ]" 
    right: 
      - icon: bi-cup-hot-fill
        href: "https://www.vilijcorps.org/" 
      - icon: github
        href: https://github.com/vilij-corps/vilij
      - icon: bi-chat-square-fill
        href: https://github.com/vilij-corps/vilij/discussions
      - icon: bi-envelope-at-fill 
        href: "https://www.vilijcorps.org/contact.html" 

format:
  html:
    toc: true
    toc-location: right
    theme: 
    - cosmo
    - assets/custom.scss
    page-layout: full