# Gameology Overview

As designers and developers of ==Kompreni?==, our goal is to make a **great** game. That is the ambition of every indie to AAA game developer.  But let's face the harsh reality that it is easier, perhaps even more likely, to make a bad game.

> Another risk is placing high hopes on games designed for the public good—as many nonprofits, health organizations, and social enterprises are doing—without realizing that bad game  design can undermine the most noble of ambitions. It’s quite possible to make terrible, dull, and unappealing games for learning or training or health. We need to have a language for discerning among these games—are they doing their job well or poorly? How can you tell? What makes them good?

In his book Finding Flow, Csikzentmihalyi and his colleagues studied people in a state of *flow*, identifying eight factors that define the optimal state for getting in the zone:

- a challenging activity requiring skill 
- a merging of action and awareness 
- clear goals 
- direct, immediate feedback 
- concentration on the task at hand 
- a sense of control 
- a loss of self-consciousness 
- an altered sense of time 

The application to video games is compelling and provides a useful measure for evaluating the game experience and potential satisfaction of the player. The role of the flow state in games was a point of specific mention for Csikzentmihalyi, observing how games have been *developed over the centuries for the express purpose of enriching life with enjoyable experiences,* as excellent producers of flow in human beings.

How Games Move Us, Emotion by Design


### What can we learn from others...

Oxenfree, Detention, Deadlight, Tails Noir, Creaks, Machinarium, Dream Alone, Orphan, OddPlanet, Pinstripe, Typoman, Toby, Mosaic, Overland, Disco Elysium, The Swapper, This War of Mine, Huntdown, Journey, My Memory of Us, Gris, Cloudpunk, Beholder 2, The Missing, Nivalis, Liberated, Narita Boy, Shady Part of Me, Book of Travels, White Shadows, Dead Static Drive, Ami, Signalis, The Plane Effect, Replaced, Endzone 2, Calvino Noir, DARQ, Eastwood, INMOST, INSIDE, Monochroma, Northern Lights, Project Highrise