# Visual Novels

A visual novel (VN) is a form of digital interactive fiction. Visual novels are often associated with the medium of video games, combining a textual narrative with static or animated illustrations and a varying degree of interactivity.

Visual novel (abbreviated as VN from now on) is a genre of gaming heavily focused on text-based storytelling, originated from Japan.

Visual novels are a type of video game that prioritize the story being told over gameplay functions. They are primarily narrative-driven, offering an immersive experience through the merging of art, sound and dialogue.

I can tell you right now that VNs have some of the best narrative experiences that you can’t quite find anywhere else. The combination of beautiful 2D art, great writing, brilliant voice acting, fantastic music, and some well-thought-out choices can make for an immersive experience that even the most expensive triple-A games can’t rival. The best visual novels also have a perfect ratio of fun/artistic value that is very rarely achieved in other mediums, where thought-provoking themes and sublime emotions are married with a real page-clicker story.


- Advancement: Players do not guide a character the way they would in a traditional video game. Instead, they advance the story by clicking in targeted regions to refresh the text.
- Complexity: Some visual novels become quite complex, with multiple branching storylines that take the player down completely different paths depending on their choices. These games can have multiple endings, too, determined by the exact choices you make in the game.
- Interactivity: Visual novel video games do involve some interactive elements, although the focus remains squarely on the storyline. The gameplay allows the player to determine in which direction the main character’s story should progress, enabling the player to feel involved in the narrative.
- Storyline: The appeal of a visual novel comes down to the story being told. Traditional video games often have a serviceable story, but there is not much depth to the characters or the world. A visual novel goes as deep as a traditional book, which means that the player gets all the same satisfaction as they would if they were reading prose—which, technically, they are.
- Text: A visual novel video game has large text boxes on the screen that show the prose as the story progresses, with backgrounds that depict the scene at hand. The experience is akin to reading a comic book, in that there are visuals and a narrative, but there is much more text on the screen than on a comic book page.

### What Makes a Visual Novel Boring?

Whether you’re curious but hesitant to dip your toes into the VN experience or considering creating one of your own, it’s worth taking a moment to consider where (some) visual novels go wrong. Recognizing these potential flaws now will make them easier to spot and avoid later.
- Tedious Dialogue: VNs need to strike a precarious balance between brevity and clarity...“skippables”
- Cookie Cutter Characters: failing to take these vessels and fill them with unique personalities and traits can quickly dry up a story’s potential.
- Shallow Relationships: every VN relies on interactions between the player character and supporting cast to move the story forward.

### For education

Visual novels are vital learning tools that promote student satisfaction and help them acquire the skills and knowledge needed to solve problems. They use interactive narrative designs to create a list of effective teaching strategies to enhance user experience.

### Let's have a look

World of Horror

Visual Novels
https://emmarie.sites.gettysburg.edu/visual-novels/is-a-visual-novel/

How to get into visual novels, the most underappreciated genre of gaming
https://medium.com/@fsnthang30/how-to-get-into-visual-novels-the-most-underappreciated-genre-of-gaming-31784a0763cf


Bin Rubaia'an MA. Visual Novels in Maxillofacial Surgery Education: A Hidden Gem. Cureus. 2023 Aug 8;15(8):e43125. doi: 10.7759/cureus.43125. PMID: 37692711; PMCID: PMC10483578.


Visual Novels: 5 Characteristics of Visual Novel Video Games
https://www.masterclass.com/articles/visual-novels-explained-plus-notable-visual-novel-video-games

Why (Some) Visual Novels Are Boring
https://storytellerkim.com/index.php/2020/11/20/why-some-visual-novels-are-boring/