# Moving Images

### The Mitchells Vs. The Machines (2021)

_The Mitchells vs. the Machines_ is a sci-fi comedy film that's centered on the titular family's experiences after the robot apocalypse threatens to destroy humanity. The messy family has to step up when they become the lone survivors and face Pal, the vengeful antagonist who seems to be a satirical portrayal of a much more intelligent version of Siri. With its striking visuals and gorgeous animation style, it's easy to feel absorbed by the Mitchells' misadventures during their apocalyptic road trip. More than just a movie about saving the world, it's also moving a story about acceptance and reconciliation.

### Nausicaä Of The Valley Of The Wind (1984)

Set one thousand years after the apocalyptic event known as the Seven Days of Fire, _Nausicaä of the Valley of the Wind_ tells the story of the titular princess. She must find a way to prevent the aggressive kingdom of Tolmekia from ravaging her land and harming her community, which is all part of an ancient prophecy that will change their entire reality. The renowned animated film is visually striking, especially the sequences that portray the vast forests infested with mutated bugs. The complex plot and Nausicaa's character send a clear message about humanity's relationship with nature.

### Paprika (2006)

Often cited alongside the [best sci-fi movies of the 2000s](https://screenrant.com/best-sci-fi-films-2000s-letterboxd/), _Paprika_ revolves around the story of the eponymous protagonist, who is a therapist turned dream detective. She's forced to step up and hunt down the thief responsible for taking a dangerous machine that allows its user to manipulate dreams and nightmares. In its disturbing dystopian future, humanity's dreams are endangered by the device, which has fallen into the wrong hands. The animation style perfectly complements this setting, as the line between reality and the dream world is often blurred.

### Spirited Away (2001)

A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.

### Watership Down (1978)

When the warren belonging to a community of rabbits is threatened, a brave group led by Fiver, Bigwig, Blackberry and Hazel leave their homeland in a search of a safe new haven.

### Grave of the Fireflies (1988)

In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.

### Princess Mononoke (1997)

Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.

### My Neighbor Totoro (1988)

Two sisters move to the country with their father in order to be closer to their hospitalized mother, and discover the surrounding trees are inhabited by Totoros, magical spirits of the forest. When the youngest runs away from home, the older sister seeks help from the spirits to find her.

### Fantastic Mr. Fox (2009)

The Fantastic Mr. Fox, bored with his current life, plans a heist against the three local farmers. The farmers, tired of sharing their chickens with the sly fox, seek revenge against him and his family.

	
### Cowboy Bebop: The Movie (2001)

The year is 2071. Following a terrorist bombing, a deadly virus is released on the populace of Mars and the government has issued the largest bounty in history, for the capture of whoever is behind it. The bounty hunter crew of the spaceship Bebop; Spike, Faye, Jet and Ed, take the case with hopes of cashing in the bounty. However, the mystery surrounding the man responsible, Vincent, goes deeper than they ever imagined, and they aren't the only ones hunting him.

### Waltz With Bashir (2008)

An Israeli film director interviews fellow veterans of the 1982 invasion of Lebanon to reconstruct his own memories of his term of service in that conflict.

### Chico & Rita (2010)

Chico is a young piano player with big dreams. Rita is a beautiful singer with an extraordinary voice. Music and romantic desire unites them, but their journey - in the tradition of the Latin ballad, the bolero - brings heartache and torment.

### Perfect Blue (1997)

Pop singer Mima Kirigow looks forward to a bright new career when she quits her chart-topping trio to become an actress. When she lands a role in a sexually charged murder mystery, Mima’s life begins to fall apart.