# 2.ZD Layers

As we mentioned before, 2.ZD is simply our way of referring to the KOMPRENI? approach for simulating a 2.5D / 3D environment using only 2D approaches.

This is accomplished by using two ( no pun intended ) simple techniques:

1. The assets are created in 3D authoring software and rendered to an image with effects that convey perspective and depth.
2. The assets are layered ( stacked ) in Godot to give the impression of the third dimension, a simulated position along the z axis.

Attention to detail with no unattributed artifacts.

Background

Middle ground

Interactive ground

Foreground

### Draw Order and Z-Index

Configured by order of the scene tree.

When nodes have the same z-index value, the draw order of the scene tree will take effect.

Convention is to have the player node at a z-index value equal to 0 ( zero ).

### WhY Sort?

Enabling y sort on a parent node changes the draw order of its children to use each object's y coordinate rendering from top to bottom.  To illustrate, consider a stacked deck of cards on a table.  If you were to "fan" the cards by pulling them down, you would see the concept of a y sort.

### The Parallax Effect

CanvasLayer