# It's not just a wall

One of the most common physical and visible features of the Ugandan landscape is the wall, a barrier with endless forms, that separates something from something. No two are alike, not because of design or deliberate differentiation, but rather because of the organic features that evolve over time like a sculpture formed by the hands of the environment they exist in.

As a physical construct, the 3D modelling of a wall is a trivial task.  A few primitive geometric forms, some cement texturing, and a game asset is created for a world that can be fittingly named *sterile* or *fake*. To present the prop as such in a game world is no different than using a mannequin for a character. As René Magritte would suggest, it is not a wall, and to suggest so would be lying.[^1]

The wall example reminds us of the importance of capturing the detail and uniqueness of what we represent.  The transformation from mannequin to a living human or from the primitive form of a 3d cube to an artifact so real-to-life you can imagine passing it by as you stroll the streets of the simulated world.

### Attention to detail

It's hard to measure the impact attention to detail has in a game.  Let's look at an example and judge with your own reaction how you perceive the difference.  We think your reaction is the same shared by all of us.

What you see underscores one of the core and most precious game design decisions we take in creating worlds -- **that no sight seen or utterance heard is fake**.



[^1]: Refers to the painting **The Treachery of Images** and the text printed below the pipe image reading, *this is not a pipe*.  He is quoted for explaining the painting as *The famous pipe. How people reproached me for it! And yet, could you stuff my pipe? No, it's just a representation, is it not? So if I had written on my picture "This is a pipe", I'd have been lying!**